"""Add password to user

Revision ID: 8273c43672b1
Revises: d5c5499ca7ce
Create Date: 2023-09-28 13:51:46.827049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8273c43672b1'
down_revision: Union[str, None] = 'd5c5499ca7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=False), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash', schema='auth')
    # ### end Alembic commands ###
