"""Add tables to event schema

Revision ID: b84665e6bc54
Revises: 84b6f0ebb6a0
Create Date: 2023-11-11 19:02:59.634048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84665e6bc54'
down_revision: Union[str, None] = '84b6f0ebb6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='event'
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Float(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='event'
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('parent_id_location', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id_location'], ['event.location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='event'
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='event'
    )
    op.create_table('event_category',
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['event.category.id'], ),
    sa.ForeignKeyConstraint(['id_event'], ['event.event.id'], ),
    sa.PrimaryKeyConstraint('id_event', 'id_category'),
    schema='event'
    )
    op.create_table('event_image',
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('id_image', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_event'], ['event.event.id'], ),
    sa.ForeignKeyConstraint(['id_image'], ['event.image.id'], ),
    sa.PrimaryKeyConstraint('id_event', 'id_image'),
    schema='event'
    )
    op.create_table('event_location',
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_event'], ['event.event.id'], ),
    sa.ForeignKeyConstraint(['id_location'], ['event.location.id'], ),
    sa.PrimaryKeyConstraint('id_event', 'id_location'),
    schema='event'
    )
    op.create_table('event_service',
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_event'], ['event.event.id'], ),
    sa.ForeignKeyConstraint(['id_service'], ['event.service.id'], ),
    sa.PrimaryKeyConstraint('id_event', 'id_service'),
    schema='event'
    )
    op.create_table('subscription_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_event', sa.Integer(), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('date_subscribed', sa.DateTime(), nullable=True),
    sa.Column('date_unsubscribed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_event'], ['event.event.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='event'
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_subscription', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('date_reviewed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_subscription'], ['event.subscription_event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='event'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review', schema='event')
    op.drop_table('subscription_event', schema='event')
    op.drop_table('event_service', schema='event')
    op.drop_table('event_location', schema='event')
    op.drop_table('event_image', schema='event')
    op.drop_table('event_category', schema='event')
    op.drop_table('service', schema='event')
    op.drop_table('location', schema='event')
    op.drop_table('image', schema='event')
    op.drop_table('category', schema='event')
    # ### end Alembic commands ###
